export const AUTH_USER = 'auth_user';
export const UNAUTH_USER = 'unauth_user';
export const AUTH_ERROR = 'auth_error';
export const FETCH_MESSAGE = 'fetch_message';
export const FETCH_FLASHCARDSETS = 'FETCH_FLASHCARDSETS';
export const FETCH_FLASHCARDSET = 'FETCH_FLASHCARDSET';
export const FETCH_FLASHCARDSETS_BY_USER = 'FETCH_FLASHCARDSETS_BY_USER';
export const REMOVED_FLASHCARD = 'REMOVED_FLASHCARD';
export const ADDED_FLASHCARD = 'ADDED_FLASHCARD';
export const UPDATED_FLASHCARD = 'UPDATED_FLASHCARD';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const ADDED_FLASHCARDS_IN_BULK = 'ADDED_FLASHCARDS_IN_BULK';
export const UPDATED_FLASHCARDSET = 'UPDATED_FLASHCARDSET';

export const SET_UP_STANDARD_MODE = 'SET_UP_STANDARD_MODE';
export const SET_UP_QUIZ_MODE = 'SET_UP_QUIZ_MODE';
export const SET_UP_MATCHING_GAME_MODE = 'SET_UP_MATCHING_GAME_MODE';

export const CHANGE_SEARCH = 'CHANGE_SEARCH';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const RESET = 'RESET';